targets:
  $default:
    builders:
      hive_generator|hive_generator:
        generate_for:
          include:
            - lib/features/main/data/models/vehicle_model.dart
            - lib/features/setup/data/models/business_setup_model.dart 
            - lib/features/records/data/models/vehicle_log_model.dart 